import Head from 'next/head'
// import MagicMouse from '@/components/MagicMouse'
import Hero from '@/components/Hero'
import Services from '@/components/Services'

export default function Home() {
  	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<Services />
		</>
	)
}
